#### libraries mostly used for data preprocessing

In [68]:
import numpy as np                 #numpy provides mathematical tools                         
import matplotlib.pyplot as plt    #matplotlib provides chart plotting functions
import pandas as pd                #for managing dataset

#### import dataset

In [69]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:,:-1].values  #feature matrix or matrix of independent variable-data (here -1 means all the columns except last)
Y = dataset.iloc[:,3].values    #dependent variable-data vector

#### handling missing data by refilling with mean of the column data

In [70]:
from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values = 'NaN',strategy = 'mean', axis =0) #to replace nan/missing values with mean
imputer = imputer.fit(X[:,1:3])
X[:,1:3] = imputer.transform(X[:,1:3])  #replaces these 2 colmn's missing values with mean

#### encoding categorical data -> if a column can be categroised into 2 or more groups. encoding is needed as they r generally text, but for mathematical models they should be encoded

In [71]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labelencoder_x = LabelEncoder()
X[:,0] = labelencoder_x.fit_transform(X[:,0])
labelencoder_y = LabelEncoder()
Y[:] = labelencoder_y.fit_transform(Y[:])

#what onehotencoder does is, labelenconder encodes spain=2,germany=1,france=0 but machine learning might think it as 0<1<2 but we dont
#to convey that message. hence onehotencoder encodes spain=001, france=010,germany=100 coding.---->DUMMY VARIABLE MATRIX
onehotencoder = OneHotEncoder(categorical_features = [0])
X = onehotencoder.fit_transform(X).toarray()

#note: we do not need onehotencoding for Y as it is the output column and ML model will know that its depedent and data and doesnt
#convey message of comparative values.

#### splitting data into train set and test set

In [88]:
from sklearn.cross_validation import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2, random_state =0) #random state variavle sets the value of any random answer to 0


#### feature scaling is needed to scale the feature data so that all the values are in similar range. feature scaling decreases algo running time

In [91]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [92]:
X_test

array([[-1.        ,  2.64575131, -0.77459667, -1.45882927, -0.90166297],
       [-1.        ,  2.64575131, -0.77459667,  1.98496442,  2.13981082]])

In [93]:
X_train

array([[-1.        ,  2.64575131, -0.77459667,  0.26306757,  0.12381479],
       [ 1.        , -0.37796447, -0.77459667, -0.25350148,  0.46175632],
       [-1.        , -0.37796447,  1.29099445, -1.97539832, -1.53093341],
       [-1.        , -0.37796447,  1.29099445,  0.05261351, -1.11141978],
       [ 1.        , -0.37796447, -0.77459667,  1.64058505,  1.7202972 ],
       [-1.        , -0.37796447,  1.29099445, -0.0813118 , -0.16751412],
       [ 1.        , -0.37796447, -0.77459667,  0.95182631,  0.98614835],
       [ 1.        , -0.37796447, -0.77459667, -0.59788085, -0.48214934]])

array([1, 1, 1, 0, 1, 0, 0, 1], dtype=object)